/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTarjetasIndexRouteImport } from './routes/_auth/tarjetas/index'
import { Route as AuthSaldoIndexRouteImport } from './routes/_auth/saldo/index'
import { Route as AuthRendimientosIndexRouteImport } from './routes/_auth/rendimientos/index'
import { Route as AuthEfectivoIndexRouteImport } from './routes/_auth/efectivo/index'
import { Route as AuthTarjetasEditRouteImport } from './routes/_auth/tarjetas/edit'
import { Route as AuthTarjetasAddRouteImport } from './routes/_auth/tarjetas/add'
import { Route as AuthPeriodosEditRouteImport } from './routes/_auth/periodos/edit'
import { Route as AuthPeriodosAddRouteImport } from './routes/_auth/periodos/add'
import { Route as AuthPeriodosIdRouteImport } from './routes/_auth/periodos/$id'
import { Route as AuthMovimientosIdRouteImport } from './routes/_auth/movimientos/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTarjetasIndexRoute = AuthTarjetasIndexRouteImport.update({
  id: '/tarjetas/',
  path: '/tarjetas/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSaldoIndexRoute = AuthSaldoIndexRouteImport.update({
  id: '/saldo/',
  path: '/saldo/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRendimientosIndexRoute = AuthRendimientosIndexRouteImport.update({
  id: '/rendimientos/',
  path: '/rendimientos/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEfectivoIndexRoute = AuthEfectivoIndexRouteImport.update({
  id: '/efectivo/',
  path: '/efectivo/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTarjetasEditRoute = AuthTarjetasEditRouteImport.update({
  id: '/tarjetas/edit',
  path: '/tarjetas/edit',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTarjetasAddRoute = AuthTarjetasAddRouteImport.update({
  id: '/tarjetas/add',
  path: '/tarjetas/add',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPeriodosEditRoute = AuthPeriodosEditRouteImport.update({
  id: '/periodos/edit',
  path: '/periodos/edit',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPeriodosAddRoute = AuthPeriodosAddRouteImport.update({
  id: '/periodos/add',
  path: '/periodos/add',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPeriodosIdRoute = AuthPeriodosIdRouteImport.update({
  id: '/periodos/$id',
  path: '/periodos/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMovimientosIdRoute = AuthMovimientosIdRouteImport.update({
  id: '/movimientos/$id',
  path: '/movimientos/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/movimientos/$id': typeof AuthMovimientosIdRoute
  '/periodos/$id': typeof AuthPeriodosIdRoute
  '/periodos/add': typeof AuthPeriodosAddRoute
  '/periodos/edit': typeof AuthPeriodosEditRoute
  '/tarjetas/add': typeof AuthTarjetasAddRoute
  '/tarjetas/edit': typeof AuthTarjetasEditRoute
  '/efectivo': typeof AuthEfectivoIndexRoute
  '/rendimientos': typeof AuthRendimientosIndexRoute
  '/saldo': typeof AuthSaldoIndexRoute
  '/tarjetas': typeof AuthTarjetasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/movimientos/$id': typeof AuthMovimientosIdRoute
  '/periodos/$id': typeof AuthPeriodosIdRoute
  '/periodos/add': typeof AuthPeriodosAddRoute
  '/periodos/edit': typeof AuthPeriodosEditRoute
  '/tarjetas/add': typeof AuthTarjetasAddRoute
  '/tarjetas/edit': typeof AuthTarjetasEditRoute
  '/efectivo': typeof AuthEfectivoIndexRoute
  '/rendimientos': typeof AuthRendimientosIndexRoute
  '/saldo': typeof AuthSaldoIndexRoute
  '/tarjetas': typeof AuthTarjetasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/movimientos/$id': typeof AuthMovimientosIdRoute
  '/_auth/periodos/$id': typeof AuthPeriodosIdRoute
  '/_auth/periodos/add': typeof AuthPeriodosAddRoute
  '/_auth/periodos/edit': typeof AuthPeriodosEditRoute
  '/_auth/tarjetas/add': typeof AuthTarjetasAddRoute
  '/_auth/tarjetas/edit': typeof AuthTarjetasEditRoute
  '/_auth/efectivo/': typeof AuthEfectivoIndexRoute
  '/_auth/rendimientos/': typeof AuthRendimientosIndexRoute
  '/_auth/saldo/': typeof AuthSaldoIndexRoute
  '/_auth/tarjetas/': typeof AuthTarjetasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/movimientos/$id'
    | '/periodos/$id'
    | '/periodos/add'
    | '/periodos/edit'
    | '/tarjetas/add'
    | '/tarjetas/edit'
    | '/efectivo'
    | '/rendimientos'
    | '/saldo'
    | '/tarjetas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/movimientos/$id'
    | '/periodos/$id'
    | '/periodos/add'
    | '/periodos/edit'
    | '/tarjetas/add'
    | '/tarjetas/edit'
    | '/efectivo'
    | '/rendimientos'
    | '/saldo'
    | '/tarjetas'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/register'
    | '/_auth/movimientos/$id'
    | '/_auth/periodos/$id'
    | '/_auth/periodos/add'
    | '/_auth/periodos/edit'
    | '/_auth/tarjetas/add'
    | '/_auth/tarjetas/edit'
    | '/_auth/efectivo/'
    | '/_auth/rendimientos/'
    | '/_auth/saldo/'
    | '/_auth/tarjetas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/tarjetas/': {
      id: '/_auth/tarjetas/'
      path: '/tarjetas'
      fullPath: '/tarjetas'
      preLoaderRoute: typeof AuthTarjetasIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/saldo/': {
      id: '/_auth/saldo/'
      path: '/saldo'
      fullPath: '/saldo'
      preLoaderRoute: typeof AuthSaldoIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rendimientos/': {
      id: '/_auth/rendimientos/'
      path: '/rendimientos'
      fullPath: '/rendimientos'
      preLoaderRoute: typeof AuthRendimientosIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/efectivo/': {
      id: '/_auth/efectivo/'
      path: '/efectivo'
      fullPath: '/efectivo'
      preLoaderRoute: typeof AuthEfectivoIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tarjetas/edit': {
      id: '/_auth/tarjetas/edit'
      path: '/tarjetas/edit'
      fullPath: '/tarjetas/edit'
      preLoaderRoute: typeof AuthTarjetasEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tarjetas/add': {
      id: '/_auth/tarjetas/add'
      path: '/tarjetas/add'
      fullPath: '/tarjetas/add'
      preLoaderRoute: typeof AuthTarjetasAddRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/periodos/edit': {
      id: '/_auth/periodos/edit'
      path: '/periodos/edit'
      fullPath: '/periodos/edit'
      preLoaderRoute: typeof AuthPeriodosEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/periodos/add': {
      id: '/_auth/periodos/add'
      path: '/periodos/add'
      fullPath: '/periodos/add'
      preLoaderRoute: typeof AuthPeriodosAddRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/periodos/$id': {
      id: '/_auth/periodos/$id'
      path: '/periodos/$id'
      fullPath: '/periodos/$id'
      preLoaderRoute: typeof AuthPeriodosIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/movimientos/$id': {
      id: '/_auth/movimientos/$id'
      path: '/movimientos/$id'
      fullPath: '/movimientos/$id'
      preLoaderRoute: typeof AuthMovimientosIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthMovimientosIdRoute: typeof AuthMovimientosIdRoute
  AuthPeriodosIdRoute: typeof AuthPeriodosIdRoute
  AuthPeriodosAddRoute: typeof AuthPeriodosAddRoute
  AuthPeriodosEditRoute: typeof AuthPeriodosEditRoute
  AuthTarjetasAddRoute: typeof AuthTarjetasAddRoute
  AuthTarjetasEditRoute: typeof AuthTarjetasEditRoute
  AuthEfectivoIndexRoute: typeof AuthEfectivoIndexRoute
  AuthRendimientosIndexRoute: typeof AuthRendimientosIndexRoute
  AuthSaldoIndexRoute: typeof AuthSaldoIndexRoute
  AuthTarjetasIndexRoute: typeof AuthTarjetasIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthMovimientosIdRoute: AuthMovimientosIdRoute,
  AuthPeriodosIdRoute: AuthPeriodosIdRoute,
  AuthPeriodosAddRoute: AuthPeriodosAddRoute,
  AuthPeriodosEditRoute: AuthPeriodosEditRoute,
  AuthTarjetasAddRoute: AuthTarjetasAddRoute,
  AuthTarjetasEditRoute: AuthTarjetasEditRoute,
  AuthEfectivoIndexRoute: AuthEfectivoIndexRoute,
  AuthRendimientosIndexRoute: AuthRendimientosIndexRoute,
  AuthSaldoIndexRoute: AuthSaldoIndexRoute,
  AuthTarjetasIndexRoute: AuthTarjetasIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
